# Generated by Django 3.1.7 on 2021-04-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaper', '0003_auto_20210406_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='username',
            new_name='user',
        ),
    ]
