# Generated by Django 3.1.7 on 2021-04-08 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaper', '0004_auto_20210406_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user_rating',
            new_name='author_rating',
        ),
    ]
