# Generated by Django 3.1.7 on 2021-04-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaper', '0006_auto_20210408_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_rating',
            new_name='_author_rating',
        ),
        migrations.AlterField(
            model_name='author',
            name='_author_rating',
            field=models.IntegerField(db_column='author_rating', default=0),
        ),
    ]
