# Generated by Django 3.1.7 on 2021-04-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPaper', '0008_auto_20210409_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='_author_rating',
        ),
        migrations.AddField(
            model_name='author',
            name='author_rating',
            field=models.IntegerField(default=0),
        ),
    ]
